:q
name: CI/CD for ECS with Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build and push Docker image
      - name: Build, Tag, and Push Docker image to ECR
        run: |
          IMAGE_TAG=${{ github.sha }}
          ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY=${{ secrets.ECR_REPOSITORY }}
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./docker
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      # Terraform Init
      - name: Terraform Init
        run: |
          cd infra
          terraform init -backend-config="bucket=my-ecs-terraform-state" \
                         -backend-config="key=ecs/terraform.tfstate" \
                         -backend-config="region=${{ secrets.AWS_REGION }}"

      # Terraform Plan
      - name: Terraform Plan
        run: |
          cd infra
          terraform plan -var="image_url=${{ env.image }}"

      # Terraform Apply
      - name: Terraform Apply
        run: |
          cd infra
          terraform apply -auto-approve -var="image_url=${{ env.image }}"

